# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e286d78d86ff9538fdcac440849785d301fccf6c22d9f2dac1478ae4fa33e0f9f04d4ccc51844c361aa5fd6122875770b6e406777d0bc593a36c174fe5b9e143

test:
  secret_key_base: 933afd497f161b80333958bf0bb6cc9712a11120697d0babd207913d989bd10f54936994a91e86131ce8c08bc4bf39637eb28692e365be1944da1a36b2c8c44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
